In [21]:
import pandas as pd
import numpy as np

url    = 'https://home.sis.siam.edu/registrar/student_inclass_all.asp?backto=teach_time&option=1&classid=203395&courseid=15336&acadyear=2563&semester=3&normalURL=f%5Fcmd%3D2%26officercode%3D20710%26officerid%3D20710%26officername%3D%25BC%25C8%252E%25B4%25C3%252E%2B%25B7%25D1%25C8%25B9%25D1%25C2%2B%25BE%25C5%25CD%25C2%25CA%25D8%25C7%25C3%25C3%25B3%26acadyear%3D2563%26rnd%3D44352%2E4941435185%26firstday%3D31%2F5%2F2564%26semester%3D3&avs296126231=5'
List = pd.read_html(url)

df = List[3]
df =  df.loc[3:,0:2].reset_index( drop = True).drop(0,axis=1)
df0= df.rename(columns={1:'id',2:'Name'})
df0

            id                    Name
0   6223200004   นายธนศักดิ์ จันทรัตน์
1   6223200006   นายภัทรพล ศรีเทียนทอง
2   6223200010    นายณัฐพงศ์ นาคทรัพย์
3   6223200011     นายรตนากร อักษรวรรณ
4   6223200012    นายณัฐวุฒิ แก้วประไพ
5   6223200014     นายนิวัฒน์ รัตนสาคร
6   6223200019    นายชาคริต เอี่ยมสกุล
7   6223200021    นายนนธวัช เจริญฤทธิ์
8   6223200022          นายคมสัน อำนวย
9   6223200025         นายจรัญ รักญาติ
10  6223200026     นายฐิติกานต์ อิ่มใจ
11  6223200027  นายพรพิพัฒน์ กรรฐโรจน์
12  6223200030   นายภูรินทร์ กิติจนาทร
13  6223200031     นายกรวุฒิ อิ่มอาดูร
14  6223200032  นายพงษ์เพชร พุ่มลอยฟ้า
15  6223200033       นางสาวรณิดา นพวัง
16  6223220002      นายอรรถพล เนตรวงค์
17  6224220001       นางสาวปวีณา บุญนำ

In [22]:
df       = df0.copy()
df['R1'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R2'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R3'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R4'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R5'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R6'] = df0['id'].apply(lambda x: np.random.randint(500) )


df

            id                    Name   R1   R2   R3   R4   R5   R6
0   6223200004   นายธนศักดิ์ จันทรัตน์  197    3  324  133  371  114
1   6223200006   นายภัทรพล ศรีเทียนทอง  215  324  306  325  226   37
2   6223200010    นายณัฐพงศ์ นาคทรัพย์  339  123  395  499  155  200
3   6223200011     นายรตนากร อักษรวรรณ  124  305  493  211  230  236
4   6223200012    นายณัฐวุฒิ แก้วประไพ  201  221  224  330   42  436
5   6223200014     นายนิวัฒน์ รัตนสาคร  108  411  158  409  180  469
6   6223200019    นายชาคริต เอี่ยมสกุล   67  219   41  171  479  487
7   6223200021    นายนนธวัช เจริญฤทธิ์  185  223   86  266  208  106
8   6223200022          นายคมสัน อำนวย  492  286  392  197  304  223
9   6223200025         นายจรัญ รักญาติ  259  305   46    0  359   55
10  6223200026     นายฐิติกานต์ อิ่มใจ  424  435  449  275  112   62
11  6223200027  นายพรพิพัฒน์ กรรฐโรจน์  331  410  430  396  437  143
12  6223200030   นายภูรินทร์ กิติจนาทร   84  250  282  127  292  165
13  6223200031     นายกรวุฒิ อิ่มอาดูร  342  222  407  356  225  448
14  6223200032  นายพงษ์เพชร พุ่มลอยฟ้า  206  342  147  155  287  161
15  6223200033       นางสาวรณิดา นพวัง  367  392  259  495  212    3
16  6223220002      นายอรรถพล เนตรวงค์  193  477  102   13  253  390
17  6224220001       นางสาวปวีณา บุญนำ  343  388   18  228   58  392

# ช้อ 1 . จงหาค่า $ I_1, I_2, I_3 $ โดยการเขียนโปรแกรม Python

![parrel1](circuit_1.png)