In [1]:
import pandas as pd
import numpy as np

url    = "https://home.sis.siam.edu/registrar/student_inclass_all.asp?backto=teach_time&option=1&classid=210169&courseid=15336&acadyear=2564&semester=3&normalURL=f%5Fcmd%3D2%26officercode%3D53113029%26officerid%3D20710%26officername%3D%25BC%25C8%252E%25B4%25C3%252E%2B%25B7%25D1%25C8%25B9%25D1%25C2%2B%25BE%25C5%25CD%25C2%25CA%25D8%25C7%25C3%25C3%25B3%26acadyear%3D2564%26rnd%3D44710%2E3665509259%26firstday%3D22%2F5%2F2565%26semester%3D3&avs167896254=5"
List = pd.read_html(url)

df = List[3]
df =  df.loc[3:,0:2].reset_index( drop = True).drop(0,axis=1)
df0= df.rename(columns={1:'id',2:'Name'})
df0['id']= df0['id'].astype('string')

In [4]:
df       = df0.copy()
df['E1'] = df0['id'].apply(lambda x: 10*np.random.randint(800) )
df['R1'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R2'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R3'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R4'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R5'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['R6'] = df0['id'].apply(lambda x: np.random.randint(500) )
df['choose'] = df0['id'].apply(lambda x: '1.'+str(1+int(x[-1])%3) )

df

,id,Name,E1,R1,R2,R3,R4,R5,R6,choose
0,6104200014,นายศิวรักษ์ อาจสามล,3840,169,464,38,27,162,49,1.2
1,6104200019,นายปภาณ หนูเชื้อเวียง,4050,176,181,99,471,476,492,1.1
2,6223200002,นายวรวุฒิ บุญชัย,6560,113,57,449,1,334,144,1.3
3,6223200013,นายกมลเทพ จิตรณรงค์,3390,68,126,267,110,320,117,1.1
4,6223220001,นายธีระศักดิ์ จันทร์แมน,7730,101,286,31,485,337,19,1.2
5,6223220003,นายศุภกานต์ ภูธร,3810,360,413,452,116,362,403,1.1
6,6223220005,นายนิธิ เมฆะวัฒนะ,720,83,196,88,62,75,441,1.3
7,6304200008,นางสาวปัญจรัตน์ ยุบลชิตร,6150,272,100,392,55,79,440,1.3
8,6323200001,นายอัษฎาวุธ รำพึงกิจ,6360,147,102,482,232,189,418,1.2
9,6323200003,นายธนวัฒน์ นันติ๊,1490,5,62,206,45,134,410,1.1
10,6323200004,นายยสินทร ธนานันท์,6830,409,408,389,360,153,207,1.2
11,6323200006,นายวัชรพงษ์ ทัพวัตร,2250,97,489,112,135,160,145,1.1
12,6323200007,นายสิรภพ กระแสร์ทิพย์,1220,49,133,333,328,391,446,1.2
13,6323200008,นายพฤกษ กุมพล,1750,454,405,487,1,145,84,1.3
14,6323200010,นายถิรวุฒิ จันทร์เพ็ญ,2370,208,250,161,279,213,309,1.1
15,6323200013,นายชนสิทธิ์ พ่วงจินดา,4350,95,305,360,28,449,431,1.1
16,6323200014,นายวีรวัฒน์ โพธิ์กลิ่น,5400,119,116,389,434,297,99,1.2
17,6323200017,นายกิตติภณ ลุ่ยทุ่ง,790,5,133,220,35,66,363,1.2
18,6323200019,นายชาญภูมิ เอี่ยมทศ,1510,233,210,99,474,267,43,1.1
19,6324200008,นายณัฐวัตร ขันโท,4710,105,417,411,387,285,215,1.3
20,6324200009,นายชัยพัชร์ ต่อพล,3350,63,470,209,304,458,62,1.1
21,6423200006,นายศุภชัย ปัญญาบารมี,4120,110,417,488,205,206,331,1.1
22,6424200002,นายทศพร วัฒนะพันธ์ศักดิ์,1270,3,460,416,87,150,381,1.3
23,6424200005,นางสาววรัญญา ศิลปศร,7920,289,491,457,466,196,115,1.3

# ช้อ 1.1 . จงหาค่า $ I_1, I_2, I_3 $ โดยการเขียนโปรแกรม Python

![1](https://raw.githubusercontent.com/Tuchsanai/152-333-Electrical-Engineering-Laboratory-3/master/HomeWork1/circuit_1.png)

# ช้อ 1.2 . จงหาค่า $ I_1, I_2, I_3 $ โดยการเขียนโปรแกรม Python

![1](https://raw.githubusercontent.com/Tuchsanai/152-333-Electrical-Engineering-Laboratory-3/master/HomeWork1/circuit_2.png)

# ช้อ 1.3 . จงหาค่า $ I_1, I_2, I_3 $ โดยการเขียนโปรแกรม Python

![1](https://raw.githubusercontent.com/Tuchsanai/152-333-Electrical-Engineering-Laboratory-3/master/HomeWork1/circuit_3.png)

# ข้อ 2 จงหารากของ

# $ r(s) = (s^a  -bs^{2} +cs-d)(es^f  - 1) $

In [3]:
df       = df0.copy()
df['a'] = df0['id'].apply(lambda x: np.random.randint(9) )
df['b'] = df0['id'].apply(lambda x: np.random.randint(20) )
df['c'] = df0['id'].apply(lambda x: np.random.randint(70) )
df['d'] = df0['id'].apply(lambda x: np.random.randint(100) )
df['e'] = df0['id'].apply(lambda x: np.random.randint(30) )
df['f'] = df0['id'].apply(lambda x: np.random.randint(8) )


df

            id                      Name  a   b   c   d   e  f
0   6104200014       นายศิวรักษ์ อาจสามล  0  10  19  65  15  6
1   6104200019     นายปภาณ หนูเชื้อเวียง  3   6  59  70   8  2
2   6223200002          นายวรวุฒิ บุญชัย  7  19  23  46  20  1
3   6223200013       นายกมลเทพ จิตรณรงค์  3  15   7  18   5  5
4   6223220001   นายธีระศักดิ์ จันทร์แมน  1  15  54  41   4  2
5   6223220003          นายศุภกานต์ ภูธร  3   8  53  78  20  0
6   6223220005         นายนิธิ เมฆะวัฒนะ  1  11  44  67  12  0
7   6304200008  นางสาวปัญจรัตน์ ยุบลชิตร  6   1  54  45  19  4
8   6323200001      นายอัษฎาวุธ รำพึงกิจ  0  17  62  57   1  5
9   6323200003         นายธนวัฒน์ นันติ๊  5   9  59  24  22  2
10  6323200004        นายยสินทร ธนานันท์  5  10  32  83   7  2
11  6323200006       นายวัชรพงษ์ ทัพวัตร  8  12  58  77   2  6
12  6323200007     นายสิรภพ กระแสร์ทิพย์  3  18  63  51  20  5
13  6323200008             นายพฤกษ กุมพล  6  12  19  85  11  5
14  6323200010     นายถิรวุฒิ จันทร์เพ็ญ  2  11  61  72   4  1
15  6323200013     นายชนสิทธิ์ พ่วงจินดา  6   7   4   9   0  0
16  6323200014    นายวีรวัฒน์ โพธิ์กลิ่น  1   8   0   4  24  0
17  6323200017       นายกิตติภณ ลุ่ยทุ่ง  3  19  52  88  14  5
18  6323200019       นายชาญภูมิ เอี่ยมทศ  4   1  66   1   8  2
19  6324200008          นายณัฐวัตร ขันโท  6   7  33  95  15  2
20  6324200009         นายชัยพัชร์ ต่อพล  8   7  16  64  18  4
21  6423200006      นายศุภชัย ปัญญาบารมี  8  10  38   0  13  3
22  6424200002  นายทศพร วัฒนะพันธ์ศักดิ์  5   0  68  98   1  2
23  6424200005       นางสาววรัญญา ศิลปศร  2   1  47  37   8  6